name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 12.x

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install esbuild
        run: npm install esbuild

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci


      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: num run build
